package com.eaglenet.vpn

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Intent
import android.net.VpnService
import android.os.Build
import android.os.IBinder
import android.os.ParcelFileDescriptor
import android.util.Log
import vpn.Vpn   // generated by: gomobile bind ./go/

/**
 * EagleVpnService
 *
 * Lifecycle:
 *  1. Activity calls VpnService.prepare() → user grants permission.
 *  2. Activity starts this service with ACTION_START and extras.
 *  3. We establish the TUN interface via VpnService.Builder.
 *  4. We pass the TUN fd to the Go engine (Vpn.start).
 *  5. tun2socks routes all device traffic through the configured proxy.
 *  6. On ACTION_STOP (or onDestroy) we call Vpn.stop() and close the TUN.
 */
class EagleVpnService : VpnService() {

    companion object {
        private const val TAG = "EagleVpnService"

        const val ACTION_START       = "com.eaglenet.vpn.START"
        const val ACTION_STOP        = "com.eaglenet.vpn.STOP"

        const val EXTRA_PROXY_TYPE   = "proxy_type"
        const val EXTRA_PROXY_HOST   = "proxy_host"
        const val EXTRA_PROXY_PORT   = "proxy_port"
        const val EXTRA_USERNAME     = "username"
        const val EXTRA_PASSWORD     = "password"
        const val EXTRA_DNS_ENABLED  = "dns_enabled"
        const val EXTRA_DNS_SERVER   = "dns_server"

        // Broadcast actions emitted to MainActivity
        const val BROADCAST_CONNECTED    = "com.eaglenet.vpn.CONNECTED"
        const val BROADCAST_DISCONNECTED = "com.eaglenet.vpn.DISCONNECTED"
        const val BROADCAST_ERROR        = "com.eaglenet.vpn.ERROR"
        const val EXTRA_ERROR_MSG        = "error_msg"

        private const val CHANNEL_ID = "eaglenet_vpn"
        private const val NOTIF_ID   = 101
        private const val TUN_MTU    = 1500
    }

    private var tunPfd: ParcelFileDescriptor? = null

    // ─── Service entry point ────────────────────────────────────────────────

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        when (intent?.action) {
            ACTION_START -> startVpn(intent)
            ACTION_STOP  -> stopVpn()
        }
        return START_STICKY
    }

    override fun onRevoke() {
        // Called by Android when user revokes VPN permission externally.
        Log.w(TAG, "VPN permission revoked")
        stopVpn()
    }

    override fun onDestroy() {
        stopVpn()
        super.onDestroy()
    }

    // ─── Connect ────────────────────────────────────────────────────────────

    private fun startVpn(intent: Intent) {
        val proxyType  = intent.getStringExtra(EXTRA_PROXY_TYPE)  ?: "socks5"
        val proxyHost  = intent.getStringExtra(EXTRA_PROXY_HOST)  ?: ""
        val proxyPort  = intent.getIntExtra   (EXTRA_PROXY_PORT,  1080)
        val user       = intent.getStringExtra(EXTRA_USERNAME)    ?: ""
        val pass       = intent.getStringExtra(EXTRA_PASSWORD)    ?: ""
        val dnsEnabled = intent.getBooleanExtra(EXTRA_DNS_ENABLED, false)
        val dnsServer  = intent.getStringExtra(EXTRA_DNS_SERVER)  ?: "223.5.5.5"

        if (proxyHost.isBlank()) {
            broadcast(BROADCAST_ERROR, "Proxy host is empty")
            stopSelf()
            return
        }

        // ── Build TUN interface ──────────────────────────────────────────
        val builder = Builder()
            .setSession("EagleNet")
            .setMtu(TUN_MTU)
            // Internal VPN address — must not clash with real network.
            .addAddress("10.88.0.1", 30)
            // Route everything except the proxy server itself through TUN.
            // This prevents the infinite loop where proxy traffic re-enters the VPN.
            .apply {
                if (isIpAddress(proxyHost)) {
                    RouteUtils.routesExcluding(proxyHost).forEach { r ->
                        addRoute(r.address, r.prefix)
                    }
                } else {
                    // Hostname proxy — we can't exclude by IP at build time.
                    // Route everything; tun2socks will protect its own socket
                    // on supported kernels via SO_MARK if available.
                    addRoute("0.0.0.0", 0)
                }
                // IPv6 full route
                addRoute("::", 0)
            }
            // DNS
            .apply {
                if (dnsEnabled && dnsServer.isNotBlank()) {
                    addDnsServer(dnsServer)
                } else {
                    // Sane public defaults (AliDNS + RethinkDNS)
                    addDnsServer("223.5.5.5")
                    addDnsServer("104.21.83.62")
                }
            }
            // Exclude our own app so config changes don't tunnel through VPN.
            .addDisallowedApplication(packageName)

        val pfd = try {
            builder.establish()
        } catch (e: Exception) {
            Log.e(TAG, "establish() failed: ${e.message}")
            broadcast(BROADCAST_ERROR, "TUN establish failed: ${e.message}")
            stopSelf()
            return
        }

        if (pfd == null) {
            broadcast(BROADCAST_ERROR, "TUN establish returned null (permission not granted?)")
            stopSelf()
            return
        }

        tunPfd = pfd
        val fd = pfd.fd.toLong()

        // ── Start Go engine ──────────────────────────────────────────────
        val errMsg = Vpn.start(
            fd,
            proxyType,
            proxyHost,
            proxyPort.toLong(),
            user,
            pass,
            if (dnsEnabled) dnsServer else ""
        )

        if (errMsg.isNotEmpty()) {
            Log.e(TAG, "Go engine start failed: $errMsg")
            pfd.close()
            tunPfd = null
            broadcast(BROADCAST_ERROR, errMsg)
            stopSelf()
            return
        }

        Log.i(TAG, "VPN connected — proxy=$proxyType://$proxyHost:$proxyPort")
        startForeground(NOTIF_ID, buildNotification(proxyHost, proxyPort))
        broadcast(BROADCAST_CONNECTED)
    }

    // ─── Disconnect ──────────────────────────────────────────────────────────

    private fun stopVpn() {
        try {
            Vpn.stop()
        } catch (e: Exception) {
            Log.w(TAG, "Vpn.stop() threw: ${e.message}")
        }
        try {
            tunPfd?.close()
        } catch (e: Exception) {
            Log.w(TAG, "tunPfd.close() threw: ${e.message}")
        }
        tunPfd = null

        stopForeground(STOP_FOREGROUND_REMOVE)
        broadcast(BROADCAST_DISCONNECTED)
        stopSelf()
        Log.i(TAG, "VPN disconnected")
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private fun broadcast(action: String, errorMsg: String? = null) {
        val intent = Intent(action)
        errorMsg?.let { intent.putExtra(EXTRA_ERROR_MSG, it) }
        sendBroadcast(intent)
    }

    private fun isIpAddress(host: String): Boolean =
        host.matches(Regex("""\d{1,3}(\.\d{1,3}){3}"""))

    // ─── Notification ────────────────────────────────────────────────────────

    private fun buildNotification(host: String, port: Int): Notification {
        ensureNotificationChannel()

        val pi = PendingIntent.getActivity(
            this, 0,
            Intent(this, MainActivity::class.java),
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT
        )

        val stopPi = PendingIntent.getService(
            this, 1,
            Intent(this, EagleVpnService::class.java).apply { action = ACTION_STOP },
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT
        )

        val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            Notification.Builder(this, CHANNEL_ID)
        } else {
            @Suppress("DEPRECATION")
            Notification.Builder(this)
        }

        return builder
            .setContentTitle("EagleNet  ●  Connected")
            .setContentText("$host : $port")
            .setSmallIcon(android.R.drawable.ic_lock_lock)
            .setContentIntent(pi)
            .setOngoing(true)
            .addAction(
                android.R.drawable.ic_menu_close_clear_cancel,
                "Disconnect",
                stopPi
            )
            .build()
    }

    private fun ensureNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val ch = NotificationChannel(
                CHANNEL_ID,
                "VPN Status",
                NotificationManager.IMPORTANCE_LOW
            ).apply {
                description = "Shows VPN connection status"
                setShowBadge(false)
            }
            getSystemService(NotificationManager::class.java)
                .createNotificationChannel(ch)
        }
    }

    // VpnService requires we return null from onBind for non-IPC uses.
    override fun onBind(intent: Intent?): IBinder? = super.onBind(intent)
}
